import { writeFile } from "fs/promises"
import { stringify } from "../parser/stringify"
import { table } from "console"

/**
 * Create an initial WireGuard server configuration file.
 *
 * This helper builds a production-ready `[Interface]` section that includes
 * Address/ListenPort/PrivateKey plus optional DNS, MTU, routing table, and
 * lifecycle hooks (PostUp/PostDown). If no custom hooks are provided the
 * function injects sane iptables masquerading rules that match `wg-quick`.
 *
 * @param filepath Absolute path where the config will be written
 * (e.g., `/etc/wireguard/wg0.conf`).
 * @param options Configuration options
 * @param options.privateKey Server private key (required).
 * @param options.port UDP listen port, defaults to `51820`.
 * @param options.ip Server address prefix (no CIDR), defaults to `10.0.0.1`.
 * @param options.interface Outbound interface for the default NAT rules,
 * defaults to `eth0`.
 * @param options.dns Optional DNS server to push to clients (writes `DNS =`).
 * @param options.postUp Optional list of commands to run after the interface
 * starts. When provided these completely replace the autogenerated iptables
 * rules. Items are concatenated with `;` to satisfy WireGuard syntax.
 * @param options.postDown Optional teardown commands; behaves like `postUp`.
 * @param options.mtu Optional MTU override written to the interface section.
 * @param options.table Optional routing table setting (`"auto"`, `"off"`, or a
 * custom table identifier).
 * @returns Promise that resolves when the config file has been written.
 * @throws If the file cannot be written (permissions, IO errors, etc.).
 *
 * @example
 * ```ts
 * await initConf("/etc/wireguard/wg0.conf", {
 *   privateKey: serverKeys.privateKey,
 *   port: 51820,
 *   ip: "10.0.0.1",
 *   dns: "1.1.1.1",
 *   mtu: "1380",
 *   postUp: [
 *     "iptables -A INPUT -i %i -j ACCEPT",
 *     "iptables -A FORWARD -i %i -j ACCEPT"
 *   ],
 *   postDown: [
 *     "iptables -D INPUT -i %i -j ACCEPT",
 *     "iptables -D FORWARD -i %i -j ACCEPT"
 *   ]
 * })
 * // Ready for: wg-quick up wg0
 * ```
 */
export const initConf = async (filepath: string, options: {
    port?: number
    ip?: string,
    privateKey: string
    interface?: string
    dns?: string
    postUp?: string[]
    postDown?: string[]
    mtu?: string
    table?: string | "auto" | "off"
}) => {
    const Interface = {
        Address: `${options.ip || "10.0.0.1"}/24`,
        ListenPort: options.port || 51820,
        PrivateKey: options.privateKey,
        DNS:  options.dns,
        MTU: options.mtu,
        Table: options.table,
        PostUp:  options.postUp ? options.postUp.join(";")  :  `iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o ${options.interface || "eth0"} -j MASQUERADE`,
        PostDown: options.postDown ? options.postDown.join(";") : `iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o ${options.interface || "eth0"} -j MASQUERADE`
    }

    const newFile = stringify({
        Interface
    })
    await writeFile(filepath, newFile)
}